-- better-auth schema (operator auth: email+password, cookie sessions, admin
-- plugin roles). Generated by `@better-auth/cli generate`. Quoted, mixed-case
-- identifiers are what better-auth queries by. Replaces the custom operators
-- table + hand-rolled JWT.

CREATE TABLE IF NOT EXISTS "user" (
    "id"            text NOT NULL PRIMARY KEY,
    "name"          text NOT NULL,
    "email"         text NOT NULL UNIQUE,
    "emailVerified" boolean NOT NULL,
    "image"         text,
    "createdAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "role"          text,
    "banned"        boolean,
    "banReason"     text,
    "banExpires"    timestamptz
);

CREATE TABLE IF NOT EXISTS "session" (
    "id"             text NOT NULL PRIMARY KEY,
    "expiresAt"      timestamptz NOT NULL,
    "token"          text NOT NULL UNIQUE,
    "createdAt"      timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"      timestamptz NOT NULL,
    "ipAddress"      text,
    "userAgent"      text,
    "userId"         text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
    "impersonatedBy" text
);

CREATE TABLE IF NOT EXISTS "account" (
    "id"                    text NOT NULL PRIMARY KEY,
    "accountId"             text NOT NULL,
    "providerId"            text NOT NULL,
    "userId"                text NOT NULL REFERENCES "user" ("id") ON DELETE CASCADE,
    "accessToken"           text,
    "refreshToken"          text,
    "idToken"               text,
    "accessTokenExpiresAt"  timestamptz,
    "refreshTokenExpiresAt" timestamptz,
    "scope"                 text,
    "password"              text,
    "createdAt"             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"             timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "verification" (
    "id"         text NOT NULL PRIMARY KEY,
    "identifier" text NOT NULL,
    "value"      text NOT NULL,
    "expiresAt"  timestamptz NOT NULL,
    "createdAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "session_userId_idx" ON "session" ("userId");
CREATE INDEX IF NOT EXISTS "account_userId_idx" ON "account" ("userId");
CREATE INDEX IF NOT EXISTS "verification_identifier_idx" ON "verification" ("identifier");

-- Retire the custom operators table (replaced by "user").
DROP TABLE IF EXISTS operators;
