apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "novamail.fullname" . }}-delivery
  labels:
    {{- include "novamail.labels" . | nindent 4 }}
    app.kubernetes.io/component: delivery
spec:
  replicas: {{ .Values.delivery.replicas }}
  selector:
    matchLabels:
      {{- include "novamail.delivery.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "novamail.delivery.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: delivery
          image: {{ include "novamail.deliveryImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            {{- include "novamail.depsEnvFrom" . | nindent 12 }}
          env:
            {{- range $k, $v := .Values.delivery.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            - name: NOVAMAIL_SMARTHOST_ADDR
              value: {{ .Values.delivery.smarthost.addr | quote }}
            - name: NOVAMAIL_SMARTHOST_TLS
              value: {{ .Values.delivery.smarthost.tls | quote }}
            - name: NOVAMAIL_SMARTHOST_INSECURE
              value: {{ .Values.delivery.smarthost.insecure | quote }}
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /readyz, port: http }
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            {{- toYaml .Values.delivery.resources | nindent 12 }}
          volumeMounts:
            - name: bodies
              mountPath: {{ .Values.bodyStore.mountPath }}
      volumes:
        - name: bodies
          {{- if .Values.bodyStore.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "novamail.fullname" . }}-bodies
          {{- else }}
          emptyDir: {}
          {{- end }}
