{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "novamail.fullname" . }}-ingress
  labels:
    {{- include "novamail.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "novamail.ingress.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novamail.fullname" . }}-delivery
  labels:
    {{- include "novamail.labels" . | nindent 4 }}
    app.kubernetes.io/component: delivery
spec:
  type: ClusterIP
  selector:
    {{- include "novamail.delivery.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "novamail.fullname" . }}-delivery
  labels:
    {{- include "novamail.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "novamail.delivery.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "novamail.fullname" . }}-dsn
  labels:
    {{- include "novamail.labels" . | nindent 4 }}
    app.kubernetes.io/component: dsn
spec:
  type: ClusterIP
  selector:
    {{- include "novamail.dsn.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "novamail.fullname" . }}-dsn
  labels:
    {{- include "novamail.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "novamail.dsn.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
