// Package db is the thin Postgres access layer for message metadata and the
// per-attempt event log that backs the tracing UI. Config/audit tables are
// owned by the Admin API (M4); this package covers the data-plane writes.
package db

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/azrtydxb/novamail/internal/model"
)

// DB wraps a pgx pool.
type DB struct{ pool *pgxpool.Pool }

// Open creates a connection pool from a DSN.
func Open(ctx context.Context, dsn string) (*DB, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("pgx pool: %w", err)
	}
	return &DB{pool: pool}, nil
}

func (d *DB) Close() { d.pool.Close() }

// Ping checks connectivity (for readiness).
func (d *DB) Ping(ctx context.Context) error { return d.pool.Ping(ctx) }

// InsertMessage records a newly accepted message in 'queued' status and logs a
// 'queued' event. The message id is generated by the caller (also the body key).
func (d *DB) InsertMessage(ctx context.Context, id string, env model.Envelope, bodyRef model.BodyRef) error {
	tx, err := d.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck // rollback after commit is a no-op

	if _, err := tx.Exec(ctx,
		`INSERT INTO messages (id, mail_from, rcpt_to, body_ref, body_backend, status)
		 VALUES ($1,$2,$3,$4,$5,'queued')`,
		id, env.MailFrom, env.RcptTo, bodyRef.Key, bodyRef.Backend,
	); err != nil {
		return fmt.Errorf("insert message: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`INSERT INTO message_events (message_id, kind) VALUES ($1,'queued')`, id,
	); err != nil {
		return fmt.Errorf("insert event: %w", err)
	}
	return tx.Commit(ctx)
}

// RecordAttempt updates the message status, bumps attempts, and appends an event.
func (d *DB) RecordAttempt(ctx context.Context, id, status, kind, provider, detail string) error {
	tx, err := d.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	if _, err := tx.Exec(ctx,
		`UPDATE messages SET status=$2, attempts=attempts+1, updated_at=now() WHERE id=$1`,
		id, status,
	); err != nil {
		return fmt.Errorf("update message: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`INSERT INTO message_events (message_id, kind, provider, detail) VALUES ($1,$2,$3,$4)`,
		id, kind, provider, detail,
	); err != nil {
		return fmt.Errorf("insert event: %w", err)
	}
	return tx.Commit(ctx)
}
