// Package db is the thin Postgres access layer for message metadata and the
// per-attempt event log that backs the tracing UI. Config/audit tables are
// owned by the Admin API (M4); this package covers the data-plane writes.
package db

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"golang.org/x/crypto/bcrypt"

	"github.com/azrtydxb/novamail/internal/model"
)

// ErrAuth is returned when authentication fails (unknown user or bad password).
var ErrAuth = errors.New("authentication failed")

// DB wraps a pgx pool.
type DB struct{ pool *pgxpool.Pool }

// Open creates a connection pool from a DSN.
func Open(ctx context.Context, dsn string) (*DB, error) {
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return nil, fmt.Errorf("pgx pool: %w", err)
	}
	return &DB{pool: pool}, nil
}

func (d *DB) Close() { d.pool.Close() }

// Ping checks connectivity (for readiness).
func (d *DB) Ping(ctx context.Context) error { return d.pool.Ping(ctx) }

// Authenticate verifies a username/password against the accounts table and
// returns the account on success. Returns ErrAuth on unknown user or mismatch.
func (d *DB) Authenticate(ctx context.Context, username, password string) (*model.Account, error) {
	var (
		acc  model.Account
		hash string
	)
	err := d.pool.QueryRow(ctx,
		`SELECT id, username, password_hash, allowed_sender_domains
		   FROM accounts WHERE username=$1`, username,
	).Scan(&acc.ID, &acc.Username, &hash, &acc.AllowedSenderDomains)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrAuth
	}
	if err != nil {
		return nil, fmt.Errorf("query account: %w", err)
	}
	if bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) != nil {
		return nil, ErrAuth
	}
	return &acc, nil
}

// LastDetail returns the most recent event detail for a message (used by the
// DSN generator to quote the upstream diagnostic). Empty string if none.
func (d *DB) LastDetail(ctx context.Context, id string) (string, error) {
	var detail string
	err := d.pool.QueryRow(ctx,
		`SELECT coalesce(detail,'') FROM message_events
		  WHERE message_id=$1 ORDER BY at DESC LIMIT 1`, id,
	).Scan(&detail)
	if errors.Is(err, pgx.ErrNoRows) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("last detail: %w", err)
	}
	return detail, nil
}

// InsertMessage records a newly accepted message in 'queued' status and logs a
// 'queued' event. The message id is generated by the caller (also the body key).
func (d *DB) InsertMessage(ctx context.Context, id string, env model.Envelope, bodyRef model.BodyRef) error {
	tx, err := d.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck // rollback after commit is a no-op

	if _, err := tx.Exec(ctx,
		`INSERT INTO messages (id, mail_from, rcpt_to, body_ref, body_backend, status)
		 VALUES ($1,$2,$3,$4,$5,'queued')`,
		id, env.MailFrom, env.RcptTo, bodyRef.Key, bodyRef.Backend,
	); err != nil {
		return fmt.Errorf("insert message: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`INSERT INTO message_events (message_id, kind) VALUES ($1,'queued')`, id,
	); err != nil {
		return fmt.Errorf("insert event: %w", err)
	}
	return tx.Commit(ctx)
}

// RecordAttempt updates the message status, bumps attempts, and appends an event.
func (d *DB) RecordAttempt(ctx context.Context, id, status, kind, provider, detail string) error {
	tx, err := d.pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx) //nolint:errcheck

	if _, err := tx.Exec(ctx,
		`UPDATE messages SET status=$2, attempts=attempts+1, updated_at=now() WHERE id=$1`,
		id, status,
	); err != nil {
		return fmt.Errorf("update message: %w", err)
	}
	if _, err := tx.Exec(ctx,
		`INSERT INTO message_events (message_id, kind, provider, detail) VALUES ($1,$2,$3,$4)`,
		id, kind, provider, detail,
	); err != nil {
		return fmt.Errorf("insert event: %w", err)
	}
	return tx.Commit(ctx)
}
